opec/opec/urls.py
from django.urls import include, path

from .views import opec, competitors, evaluators

urlpatterns = [
    path('', opec.home, name='home'),
    path('exams/', opec.exams, name='exams'),
    path('contact/', opec.contact, name='contact'),

    path('competitors/', include(([
        path('', competitors.ExamListView.as_view(), name='exam_list'),
        path('interests/', competitors.CompetitorInterestsView.as_view(), name='competitor_interests'),
        path('taken/', competitors.TakenExamListView.as_view(), name='taken_exam_list'),
        path('exam/<int:pk>/', competitors.take_exam, name='take_exam'),
    ], 'opec'), namespace='competitors')),

    path('evaluators/', include(([
        path('', evaluators.ExamListView.as_view(), name='exam_change_list'),
        path('exam/add/', evaluators.ExamCreateView.as_view(), name='exam_add'),
        path('exam/<int:pk>/', evaluators.ExamUpdateView.as_view(), name='exam_change'),
        path('exam/<int:pk>/delete/', evaluators.ExamDeleteView.as_view(), name='exam_delete'),
        path('exam/<int:pk>/results/', evaluators.ExamResultsView.as_view(), name='exam_results'),
        path('exam/<int:pk>/question/add/', evaluators.question_add, name='question_add'),
        path('exam/<int:exam_pk>/question/<int:question_pk>/', evaluators.question_change, name='question_change'),
        path('exam/<int:exam_pk>/question/<int:question_pk>/delete/', evaluators.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'opec'), namespace='evaluators')),
]

opec/project/urls.py
from django.contrib import admin
from django.urls import path,include
from opec.views import opec, competitors, evaluators

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('opec.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', opec.SignUpView.as_view(), name='signup'),
    path('accounts/signup/competitor/', competitors.CompetitorSignUpView.as_view(), name='competitor_signup'),
    path('accounts/signup/evaluator/', evaluators.EvaluatorSignUpView.as_view(), name='evaluator_signup'),
]

opec/opec/views/competitors.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import competitor_required
from ..forms import CompetitorInterestsForm, CompetitorSignUpForm, TakeExamForm
from ..models import Exam, Competitor, TakenExam, User


class CompetitorSignUpView(CreateView):
    model = User
    form_class = CompetitorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'competitor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('competitors:exam_list')


@method_decorator([login_required, competitor_required], name='dispatch')
class CompetitorInterestsView(UpdateView):
    model = Competitor
    form_class = CompetitorInterestsForm
    template_name = 'opec/competitors/interests_form.html'
    success_url = reverse_lazy('competitors:exam_list')

    def get_object(self):
        return self.request.user.competitor

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, competitor_required], name='dispatch')
class ExamListView(ListView):
    model = Exam
    ordering = ('name', )
    context_object_name = 'exams'
    template_name = 'opec/competitors/exam_list.html'

    def get_queryset(self):
        competitor = self.request.user.competitor
        competitor_interests = competitor.interests.values_list('pk', flat=True)
        taken_exams = competitor.exams.values_list('pk', flat=True)
        queryset = Exam.objects.filter(subject__in=competitor_interests) \
            .exclude(pk__in=taken_exams) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, competitor_required], name='dispatch')
class TakenExamListView(ListView):
    model = TakenExam
    context_object_name = 'taken_exams'
    template_name = 'opec/competitors/taken_exam_list.html'

    def get_queryset(self):
        queryset = self.request.user.competitor.taken_exams \
            .select_related('exam', 'exam__subject') \
            .order_by('exam__name')
        return queryset


@login_required
@competitor_required
def take_exam(request, pk):
    exam = get_object_or_404(Exam, pk=pk)
    competitor = request.user.competitor

    if competitor.exams.filter(pk=pk).exists():
        return render(request, 'competitors/taken_exam.html')

    total_questions = exam.questions.count()
    unanswered_questions = competitor.get_unanswered_questions(exam)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeExamForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                competitor_answer = form.save(commit=False)
                competitor_answer.competitor = competitor
                competitor_answer.save()
                if competitor.get_unanswered_questions(exam).exists():
                    return redirect('competitors:take_exam', pk)
                else:
                    correct_answers = competitor.exam_answers.filter(answer__question__exam=exam, answer__is_correct=True).count()
                    score = round((correct_answers / total_questions) * 100.0, 2)
                    TakenExam.objects.create(competitor=competitor, exam=exam, score=score)
                    if score < 50.0:
                        messages.warning(request, 'Better luck next time! Your score for the exam %s was %s.' % (exam.name, score))
                    else:
                        messages.success(request, 'Congratulations! You completed the exam %s with success! You scored %s points.' % (exam.name, score))
                    return redirect('competitors:exam_list')
    else:
        form = TakeExamForm(question=question)

    return render(request, 'opec/competitors/take_exam_form.html', {
        'exam': exam,
        'question': question,
        'form': form,
        'progress': progress
    })

opec/opec/views/evaluators.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from ..decorators import evaluator_required
from ..forms import BaseAnswerInlineFormSet, QuestionForm, EvaluatorSignUpForm
from ..models import Answer, Question, Exam, User


class EvaluatorSignUpView(CreateView):
    model = User
    form_class = EvaluatorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'evaluator'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('evaluators:exam_change_list')


@method_decorator([login_required, evaluator_required], name='dispatch')
class ExamListView(ListView):
    model = Exam
    ordering = ('name', )
    context_object_name = 'exams'
    template_name = 'opec/evaluators/exam_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.exams \
            .select_related('subject') \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_exams', distinct=True))
        return queryset


@method_decorator([login_required, evaluator_required], name='dispatch')
class ExamCreateView(CreateView):
    model = Exam
    fields = ('name', 'subject', )
    template_name = 'opec/evaluators/exam_add_form.html'

    def form_valid(self, form):
        exam = form.save(commit=False)
        exam.owner = self.request.user
        exam.save()
        messages.success(self.request, 'The exam was created with success! Go ahead and add some questions now.')
        return redirect('evaluators:exam_change', exam.pk)


@method_decorator([login_required, evaluator_required], name='dispatch')
class ExamUpdateView(UpdateView):
    model = Exam
    fields = ('name', 'subject', )
    context_object_name = 'exam'
    template_name = 'opec/evaluators/exam_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing exams that belongs
        to the logged in user.
        '''
        return self.request.user.exams.all()

    def get_success_url(self):
        return reverse('evaluators:exam_change', kwargs={'pk': self.object.pk})


@method_decorator([login_required, evaluator_required], name='dispatch')
class ExamDeleteView(DeleteView):
    model = Exam
    context_object_name = 'exam'
    template_name = 'opec/evaluators/exam_delete_confirm.html'
    success_url = reverse_lazy('evaluators:exam_change_list')

    def delete(self, request, *args, **kwargs):
        exam = self.get_object()
        messages.success(request, 'The exam %s was deleted with success!' % exam.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.exams.all()


@method_decorator([login_required, evaluator_required], name='dispatch')
class ExamResultsView(DetailView):
    model = Exam
    context_object_name = 'exam'
    template_name = 'opec/evaluators/exam_results.html'

    def get_context_data(self, **kwargs):
        exam = self.get_object()
        taken_exams = exam.taken_exams.select_related('competitor__user').order_by('-date')
        total_taken_exams = taken_exams.count()
        exam_score = exam.taken_exams.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_exams': taken_exams,
            'total_taken_exams': total_taken_exams,
            'exam_score': exam_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.exams.all()


@login_required
@evaluator_required
def question_add(request, pk):
    # By filtering the exam by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # exam will be able to add questions to it.
    exam = get_object_or_404(Exam, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.exam = exam
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('evaluators:question_change', exam.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'opec/evaluators/question_add_form.html', {'exam': exam, 'form': form})


@login_required
@evaluator_required
def question_change(request, exam_pk, question_pk):
    # Simlar to the `question_add` view, this view is also managing
    # the permissions at object-level. By querying both `exam` and
    # `question` we are making sure only the owner of the exam can
    # change its details and also only questions that belongs to this
    # specific exam can be changed via this url (in cases where the
    # user might have forged/player with the url params.
    exam = get_object_or_404(Exam, pk=exam_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, exam=exam)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('evaluators:exam_change', exam.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'opec/evaluators/question_change_form.html', {
        'exam': exam,
        'question': question,
        'form': form,
        'formset': formset
    })


@method_decorator([login_required, evaluator_required], name='dispatch')
class QuestionDeleteView(DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'opec/evaluators/question_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['exam'] = question.exam
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(request, 'The question %s was deleted with success!' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(exam__owner=self.request.user)

    def get_success_url(self):
        question = self.get_object()
        return reverse('evaluators:exam_change', kwargs={'pk': question.exam_id})

opec/opec/views/opec.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_evaluator:
            return redirect('evaluators:exam_change_list')
        else:
            return redirect('competitors:exam_list')
    return render(request, 'opec/Home.html')



def exams(request):
    return render(request, 'opec/Exams.html')

def contact(request):
    return render(request, 'opec/Contact.html')

opec/opec/templates/opec/evaluators/exam_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new exam</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new exam</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'evaluators:exam_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>
{% endblock %}

opec/opec/templates/opec/evaluators/exam_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ exam.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ exam.name }}
    <a href="{% url 'evaluators:exam_results' exam.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'evaluators:exam_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a href="{% url 'evaluators:exam_delete' exam.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'evaluators:question_change' exam.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'evaluators:question_add' exam.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'evaluators:question_add' exam.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
{% endblock %}

opec/opec/templates/opec/evaluators/exam_change_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Exams</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Exams</h2>
  <a href="{% url 'evaluators:exam_add' %}" class="btn btn-primary mb-3" role="button">Add exam</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Exam</th>
          <th>Subject</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for exam in exams %}
          <tr>
            <td class="align-middle"><a href="{% url 'evaluators:exam_change' exam.pk %}">{{ exam.name }}</a></td>
            <td class="align-middle">{{ exam.subject.get_html_badge }}</td>
            <td class="align-middle">{{ exam.questions_count }}</td>
            <td class="align-middle">{{ exam.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'evaluators:exam_results' exam.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any exam yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

opec/opec/templates/opec/evaluators/exam_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:quiz_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item"><a href="{% url 'evaluators:quiz_change' exam.pk %}">{{ exam.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the exam <strong>"{{ exam.name }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'evaluators:exam_change' exam.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}

opec/opec/templates/opec/evaluators/exam_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change' exam.pk %}">{{ exam.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Results</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ exam.name }} Results</h2>

  <div class="card">
    <div class="card-header">
      <strong>Taken Exams</strong>
      <span class="badge badge-pill badge-primary float-right">Average Score: {{ exam_score.average_score|default_if_none:0.0 }}</span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Competitor</th>
          <th>Date</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_exam in taken_exams %}
          <tr>
            <td>{{ taken_exam.competitor.user.username }}</td>
            <td>{{ taken_exam.date|naturaltime }}</td>
            <td>{{ taken_exam.score }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      Total respondents: <strong>{{ total_taken_exams }}</strong>
    </div>
  </div>
{% endblock %}

opec/opec/templates/opec/evaluators/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change' exam.pk %}">{{ exam.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'evaluators:exam_change' exam.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
  </form>
{% endblock %}

opec/opec/templates/opec/evaluators/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change' exam.pk %}">{{ exam.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>10</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'evaluators:exam_change' exam.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    <a href="{% url 'evaluators:question_delete' exam.pk question.pk %}" class="btn btn-danger float-right">Delete</a>
  </form>
{% endblock %}

opec/opec/templates/opec/evaluators/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change_list' %}">My Exams</a></li>
      <li class="breadcrumb-item"><a href="{% url 'evaluators:exam_change' exam.pk %}">{{ exam.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'evaluators:question_change' exam.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'evaluators:question_change' exam.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}